import { describe, expect, it } from 'vitest'
import { attendanceSummaryForGroup, dataForAcademicYear, gradeFor, latestAcademicYearId, rosterForGroup, scheduleForDate, validateScore, weightedTotal } from '../src/domain/logic'
import { createMockData } from '../src/mock/data'
import { applyLocalMutation } from '../src/domain/mutations'
import { parseRosterRows } from '../src/features/roster/excelRoster'

describe('gradebook domain', () => {
  it('creates two academic years, six rooms and 90 fictional students', () => { const data=createMockData(); expect(data.academicYears).toHaveLength(2);expect(data.teachingGroups).toHaveLength(12); expect(data.students).toHaveLength(90); expect(rosterForGroup(data,data.teachingGroups[0].id)).toHaveLength(15) })
  it('validates total scores without turning blank into zero', () => { expect(validateScore(null,10)).toBeNull(); expect(validateScore(11,10)).toContain('10'); expect(validateScore(-1,10)).not.toBeNull() })
  it('calculates grade thresholds and weighted totals', () => { const data=createMockData(); expect(gradeFor(79,data.gradeThresholds)).toBe('3.5'); const student=data.students[0]; expect(weightedTotal(student.id,data.assessments,data.assessmentCategories,data.scores)).toBeGreaterThanOrEqual(0) })
  it('applies an attendance mutation optimistically', () => { const data=createMockData(); const current=data.attendanceRecords[0]; const next=applyLocalMutation(data,{ id:'mutation-1',entity:'AttendanceRecord',action:'attendance.update',baseVersion:current.version,createdAt:new Date().toISOString(),payload:{...current,status:'ABSENT'} }); expect(next.attendanceRecords.find((item)=>item.id===current.id)?.status).toBe('ABSENT') })
  it('links an attendance date to rooms in the weekly schedule',()=>{const data=createMockData();const monday=scheduleForDate(data,'2026-08-31');const sunday=scheduleForDate(data,'2026-08-30');expect(monday.weekday).toBe(1);expect(monday.groups.map((item)=>item.id)).toEqual([...new Set(monday.slots.map((item)=>item.teachingGroupId))]);expect(monday.groups.length).toBeGreaterThan(0);expect(sunday.groups).toHaveLength(0);expect(scheduleForDate(data,'').groups).toHaveLength(0)})
  it('defaults to the latest academic year and keeps historical data selectable',()=>{const data=createMockData();expect(latestAcademicYearId(data)).toBe('year-2569');const latest=dataForAcademicYear(data,'year-2569');const previous=dataForAcademicYear(data,'year-2568');expect(latest.academicYears).toHaveLength(2);expect(latest.teachingGroups).toHaveLength(6);expect(previous.teachingGroups).toHaveLength(6);expect(previous.terms.every((item)=>item.academicYearId==='year-2568')).toBe(true);expect(previous.attendanceSessions.length).toBeGreaterThan(0);expect(previous.assessments.length).toBeGreaterThan(0)})
  it('provides complete sample data and attendance dashboard percentages',()=>{const data=createMockData();const summary=attendanceSummaryForGroup(data,data.teachingGroups[0].id);expect(summary.days).toBe(20);expect(summary.presentPercent+summary.absentPercent+summary.leavePercent).toBeCloseTo(100,0);expect(summary.frequentAbsences.length).toBeGreaterThan(0);expect(data.teacherLeaves.length).toBeGreaterThan(1);expect(data.behaviorLogs.length).toBeGreaterThanOrEqual(data.teachingGroups.length);expect(data.finalGrades.length).toBeGreaterThan(0);expect(data.exportRequests.length).toBeGreaterThan(0)})
  it('replaces score categories optimistically',()=>{const data=dataForAcademicYear(createMockData(),'year-2569');const current=data.assessmentCategories;const records=current.map((item,index)=>({...item,weight:[35,15,20,30][index]}));const next=applyLocalMutation(data,{id:'mutation-categories',entity:'AssessmentCategory',action:'assessmentCategories.replace',baseVersion:0,createdAt:new Date().toISOString(),payload:{records,deletedIds:[]}});expect(next.assessmentCategories.reduce((sum,item)=>sum+item.weight,0)).toBe(100);expect(next.assessmentCategories[0].weight).toBe(35)})
  it('parses Thai Excel roster rows and rejects duplicate codes',()=>{const rows=[['รหัสนักเรียน','เลขที่','คำนำหน้า','ชื่อ','นามสกุล','ชื่อเล่น','หมายเหตุ'],['065001','1','นาย','กิตติ','ใจดี','กิต','แพ้ถั่ว']];expect(parseRosterRows(rows)[0]).toMatchObject({studentCode:'065001',number:1,firstName:'กิตติ',privateNote:'แพ้ถั่ว'});expect(()=>parseRosterRows([...rows,['065001','2','นางสาว','มาลี','ใจดี','ลี','']])).toThrow('รหัสนักเรียนซ้ำ')})
  it('adds a room and imports students optimistically',()=>{const data=createMockData();const now=new Date().toISOString();const room={id:'room-new',version:0,createdAt:now,updatedAt:now,gradeLevelId:data.gradeLevels[0].id,code:'M4/9',name:'ม.4/9'};const group={id:'group-new',version:0,createdAt:now,updatedAt:now,termId:data.terms[0].id,gradeLevelId:data.gradeLevels[0].id,roomId:room.id,subjectId:data.subjects[0].id,name:'คณิตศาสตร์ ม.4/9'};const withRoom=applyLocalMutation(data,{id:'mutation-room',entity:'Room',action:'room.create',baseVersion:0,createdAt:now,payload:{room,group}});expect(withRoom.rooms.some((item)=>item.id===room.id)).toBe(true);const student={...data.students[0],firstName:'แก้ไขชื่อ'};const enrollment={id:'enrollment-new',version:0,createdAt:now,updatedAt:now,teachingGroupId:group.id,studentId:student.id};const imported=applyLocalMutation(withRoom,{id:'mutation-students',entity:'Student',action:'students.import',baseVersion:0,createdAt:now,payload:{students:[student],enrollments:[enrollment]}});expect(imported.students.find((item)=>item.id===student.id)?.firstName).toBe('แก้ไขชื่อ');expect(imported.enrollments.some((item)=>item.teachingGroupId===group.id)).toBe(true)})
})
