function requestExport_(payload) {
  var ids=payload.teachingGroupIds||[]; if (!ids.length) throw apiError_('INVALID_EXPORT','กรุณาเลือกอย่างน้อยหนึ่งห้อง'); var id=Utilities.getUuid(); var now=new Date().toISOString(); var request=baseRecord_(id,{format:payload.format==='XLSX'?'XLSX':'PDF',status:'QUEUED',scope:payload.scope||'SELECTED',teachingGroupIds:ids,includeBehavior:!!payload.includeBehavior}); upsertRecord_('exportRequests',request);
  ScriptApp.newTrigger('processExportQueue').timeBased().after(1000).create(); return {jobId:id,exportRequestId:id};
}
function jobStatus_(id) { var job=findRecord_('exportRequests',id); if (!job) throw apiError_('NOT_FOUND','ไม่พบงานสร้างรายงาน'); return job; }
function processExportQueue() {
  ScriptApp.getProjectTriggers().filter(function(trigger){return trigger.getHandlerFunction()==='processExportQueue';}).forEach(function(trigger){ScriptApp.deleteTrigger(trigger);}); var job=readAll_('exportRequests').filter(function(item){return item.status==='QUEUED';})[0]; if (!job) return;
  try { job.status='RUNNING'; upsertRecord_('exportRequests',job); var file=createExportFile_(job); job.status='SUCCEEDED'; job.fileName=file.getName(); job.fileUrl=file.getUrl(); upsertRecord_('exportRequests',job); } catch(error) { job.status='FAILED'; job.error=error.message; upsertRecord_('exportRequests',job); throw error; }
}
function createExportFile_(job) {
  var temp=SpreadsheetApp.create('KruNote Export '+job.id); var groups=readAll_('teachingGroups').filter(function(group){return job.teachingGroupIds.indexOf(group.id)>=0;}); var students=readAll_('students'); var enrollments=readAll_('enrollments'); var finalGrades=readAll_('finalGrades');
  groups.forEach(function(group,index){var sheet=index===0?temp.getSheets()[0]:temp.insertSheet(); sheet.setName(group.name.replace(/[\\\/?*\[\]:]/g,'-').substring(0,31)); var roster=enrollments.filter(function(item){return item.teachingGroupId===group.id;}).map(function(item){return students.filter(function(student){return student.id===item.studentId;})[0];}).filter(Boolean).sort(function(a,b){return a.number-b.number;}); var values=[['เลขที่','รหัสนักเรียน','ชื่อ-นามสกุล','ชื่อเล่น','คะแนนรวม','เกรด']]; roster.forEach(function(student){var grade=finalGrades.filter(function(item){return item.teachingGroupId===group.id&&item.studentId===student.id;})[0]||{}; values.push([student.number,student.studentCode,student.title+student.firstName+' '+student.lastName,student.nickname,grade.total||'',grade.grade||'']);}); sheet.getRange(1,1,values.length,6).setValues(values); sheet.setFrozenRows(1); sheet.getRange(1,1,1,6).setFontWeight('bold').setBackground('#166b59').setFontColor('#ffffff'); sheet.autoResizeColumns(1,6); }); SpreadsheetApp.flush();
  var format=job.format==='XLSX'?'xlsx':'pdf'; var mime=job.format==='XLSX'?'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':'application/pdf'; var url='https://docs.google.com/spreadsheets/d/'+temp.getId()+'/export?format='+format+'&portrait=true&fitw=true&sheetnames=true&pagenumbers=true&gridlines=false'; var response=UrlFetchApp.fetch(url,{headers:{Authorization:'Bearer '+ScriptApp.getOAuthToken()}}); var blob=response.getBlob().setContentType(mime).setName('KruNote-'+Utilities.formatDate(new Date(),'Asia/Bangkok','yyyy-MM-dd')+'.'+format); var file=ensureExportFolder_().createFile(blob); DriveApp.getFileById(temp.getId()).setTrashed(true); return file;
}
