function digest_(value) { return Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,value,Utilities.Charset.UTF_8)); }
function setPin_(pin,mustChange) { if (!/^\d{4,12}$/.test(String(pin))) throw apiError_('INVALID_PIN','PIN ต้องเป็นตัวเลข 4–12 หลัก'); var salt=Utilities.getUuid(); var props=PropertiesService.getScriptProperties(); props.setProperty('PIN_SALT',salt); props.setProperty('PIN_HASH',digest_(salt+':'+pin)); props.setProperty('MUST_CHANGE_PIN',mustChange ? 'true':'false'); }
function verifyPin_(pin) {
  var cache=CacheService.getScriptCache(); var block=cache.get('pin-block'); if (block) throw apiError_('RATE_LIMITED','ลอง PIN ผิดหลายครั้ง กรุณารอ 5 นาที'); var props=PropertiesService.getScriptProperties(); if (!props.getProperty('PIN_HASH')) throw apiError_('NOT_INSTALLED','ยังไม่ได้ติดตั้งระบบ');
  var valid=digest_(props.getProperty('PIN_SALT')+':'+String(pin))===props.getProperty('PIN_HASH'); if (!valid) { var attempts=Number(cache.get('pin-attempts')||0)+1; cache.put('pin-attempts',String(attempts),300); if (attempts>=5) cache.put('pin-block','1',300); throw apiError_('INVALID_PIN','PIN ไม่ถูกต้อง'); }
  cache.remove('pin-attempts'); var token=Utilities.getUuid()+Utilities.getUuid(); var expiresAt=new Date(Date.now()+21600000).toISOString(); cache.put('session:'+digest_(token),JSON.stringify({expiresAt:expiresAt}),21600); return { token:token, expiresAt:expiresAt, mustChangePin:props.getProperty('MUST_CHANGE_PIN')==='true' };
}
function requireSession_(token) { if (!token) throw apiError_('UNAUTHORIZED','กรุณาปลดล็อกอีกครั้ง'); var raw=CacheService.getScriptCache().get('session:'+digest_(token)); if (!raw) throw apiError_('SESSION_EXPIRED','เซสชันหมดอายุ กรุณาปลดล็อกอีกครั้ง'); return JSON.parse(raw); }
function changePin_(session,currentPin,newPin) { var props=PropertiesService.getScriptProperties(); if (digest_(props.getProperty('PIN_SALT')+':'+String(currentPin))!==props.getProperty('PIN_HASH')) throw apiError_('INVALID_PIN','PIN ปัจจุบันไม่ถูกต้อง'); if (!/^\d{6,12}$/.test(String(newPin))) throw apiError_('INVALID_PIN','PIN ใหม่ต้องเป็นตัวเลข 6–12 หลัก'); if (String(currentPin)===String(newPin)) throw apiError_('INVALID_PIN','PIN ใหม่ต้องไม่ซ้ำ PIN เดิม'); setPin_(String(newPin),false); return verifyPin_(String(newPin)); }
