function baseRecord_(id,value) { var now=new Date().toISOString(); return Object.assign({id:id,version:1,createdAt:now,updatedAt:now,isMock:true},value); }

function seedRows_(collection,records) {
  if (!records.length) return;
  var sheet=sheetFor_(collection); var rows=records.map(function(item){return [item.id,JSON.stringify(item),item.version,item.updatedAt];});
  sheet.getRange(sheet.getLastRow()+1,1,rows.length,4).setValues(rows);
}

function seedMockData_() {
  var data={academicYears:[],terms:[],gradeLevels:[],rooms:[],subjects:[],teachingGroups:[],students:[],enrollments:[],scheduleSlots:[],teacherLeaves:[],attendanceSessions:[],attendanceRecords:[],assessmentCategories:[],assessments:[],assessmentTargets:[],submissions:[],scores:[],behaviorLogs:[],gradeThresholds:[],finalGrades:[],exportRequests:[]};
  var previousYear=baseRecord_('year-2568',{name:'2568',startDate:'2025-05-01',endDate:'2026-03-31',active:false});
  var previousTerm=baseRecord_('term-2568-1',{academicYearId:previousYear.id,name:'ภาคเรียนที่ 1',number:1,startDate:'2025-05-01',endDate:'2025-10-15',active:false});
  var year=baseRecord_('year-2569',{name:'2569',startDate:'2026-05-01',endDate:'2027-03-31',active:true});
  var term=baseRecord_('term-2569-1',{academicYearId:year.id,name:'ภาคเรียนที่ 1',number:1,startDate:'2026-05-01',endDate:'2026-10-15',active:true});
  data.academicYears.push(previousYear,year); data.terms.push(previousTerm,term); data.subjects.push(baseRecord_('subject-math',{code:'ค31101',name:'คณิตศาสตร์'}));
  var first=['กิตติพงษ์','ณัฐชา','ปกรณ์','ชลธิชา','ธนกฤต','พิมพ์ชนก','ภูริณัฐ','วรัญญา','ศุภกร','สิรินดา','อชิรญา','กมลชนก','นราวิชญ์','ปุณณภพ','รินรดา'];
  var last=['ใจดี','สุขใจ','แสงทอง','คำดี','บุญช่วย','วงศ์สวัสดิ์','ตั้งใจ','ศรีสุข','พิพัฒน์กุล','พรประเสริฐ','สุขเกษม','รัตนวงศ์','ชูศักดิ์','มั่นคง','สินสมบูรณ์'];
  var nick=['ต้น','มิ้น','เกม','แพรว','นนท์','มุก','ภูมิ','ใบหม่อน','กล้า','ขิม','ออม','ฟ้า','ไนท์','ปัน','ริน']; var studentIndex=0;
  [4,5,6].forEach(function(level){
    var grade=baseRecord_('grade-'+level,{code:'M'+level,name:'ม.'+level,order:level-3}); data.gradeLevels.push(grade);
    [1,2].forEach(function(roomNo){
      var room=baseRecord_('room-M'+level+'-'+roomNo,{gradeLevelId:grade.id,code:'M'+level+'/'+roomNo,name:'ม.'+level+'/'+roomNo});
      var group=baseRecord_('group-M'+level+'/'+roomNo,{termId:term.id,gradeLevelId:grade.id,roomId:room.id,subjectId:'subject-math',name:'คณิตศาสตร์ '+room.name});
      data.rooms.push(room); data.teachingGroups.push(group); data.scheduleSlots.push(baseRecord_('schedule-'+group.id,{teachingGroupId:group.id,weekday:((level+roomNo)%5)+1,period:roomNo,startTime:roomNo===1?'08:30':'09:30',endTime:roomNo===1?'09:20':'10:20'})); var groupStudentIds=[];
      for(var n=1;n<=15;n++){
        studentIndex++; var sid='student-'+studentIndex; groupStudentIds.push(sid); data.students.push(baseRecord_(sid,{studentCode:String(level)+String(roomNo)+String(n).padStart(2,'0'),number:n,title:n%2?'นาย':'นางสาว',firstName:first[n-1],lastName:last[n-1],nickname:nick[n-1],active:true,privateNote:n===5?'ติดตามงานที่ยังไม่ครบ':''}));
        data.enrollments.push(baseRecord_('enrollment-'+group.id+'-'+sid,{teachingGroupId:group.id,studentId:sid}));
      }
      for(var sessionNo=0;sessionNo<12;sessionNo++){var sessionDate=new Date();sessionDate.setDate(sessionDate.getDate()-(11-sessionNo));var sessionDateText=Utilities.formatDate(sessionDate,'Asia/Bangkok','yyyy-MM-dd');var session=baseRecord_('session-'+group.id+'-'+sessionNo,{teachingGroupId:group.id,date:sessionDateText,period:roomNo});data.attendanceSessions.push(session);groupStudentIds.forEach(function(studentId,index){var marker=(index+sessionNo+level+roomNo)%23;var status=index===0&&sessionNo%3===0?'ABSENT':marker===0?'ABSENT':marker===6?'LEAVE':marker===11?'LATE':'PRESENT';data.attendanceRecords.push(baseRecord_(session.id+':'+studentId,{sessionId:session.id,studentId:studentId,status:status}));});}
    });
  });
  [['category-work','งานและการบ้าน',30],['category-quiz','แบบทดสอบ',20],['category-midterm','กลางภาค',20],['category-final','ปลายภาค',30]].forEach(function(item){data.assessmentCategories.push(baseRecord_(item[0],{termId:term.id,name:item[1],weight:item[2]}));});
  [4,5,6].forEach(function(level){
    var groups=data.teachingGroups.filter(function(group){return group.gradeLevelId==='grade-'+level;});
    [['การบ้านบทที่ 1','ASSIGNMENT','category-work',20,'REVIEWED'],['แบบฝึกหัดประยุกต์','WORK','category-work',15,'REVIEWING'],['ชิ้นงานสรุปบท','WORK','category-work',25,'OPEN'],['แบบทดสอบย่อย 1','QUIZ','category-quiz',10,'DUE'],['สอบกลางภาค','MIDTERM','category-midterm',30,'REVIEWED'],['สอบปลายภาค','FINAL','category-final',40,'REVIEWED']].forEach(function(definition,index){
      var aid='assessment-M'+level+'-'+(index+1); var due=new Date(); due.setDate(due.getDate()+index-2);
      data.assessments.push(baseRecord_(aid,{termId:term.id,gradeLevelId:'grade-'+level,subjectId:'subject-math',categoryId:definition[2],title:definition[0],type:definition[1],status:definition[4],assignedAt:Utilities.formatDate(new Date(due.getTime()-604800000),'Asia/Bangkok','yyyy-MM-dd'),dueAt:Utilities.formatDate(due,'Asia/Bangkok','yyyy-MM-dd'),maxScore:definition[3]}));
      groups.forEach(function(group){
        data.assessmentTargets.push(baseRecord_('target-'+aid+'-'+group.id,{assessmentId:aid,teachingGroupId:group.id}));
        data.enrollments.filter(function(item){return item.teachingGroupId===group.id;}).forEach(function(enrollment,studentNo){var missing=(studentNo+index)%11===0;var late=!missing&&(studentNo+index)%7===0;var hasScore=definition[4]==='REVIEWED'||definition[4]==='REVIEWING'&&studentNo<9||definition[4]==='DUE'&&studentNo<6; data.submissions.push(baseRecord_(aid+':'+enrollment.studentId,{assessmentId:aid,studentId:enrollment.studentId,status:missing?'MISSING':late?'LATE':'SUBMITTED'})); data.scores.push(baseRecord_(aid+':'+enrollment.studentId,{assessmentId:aid,studentId:enrollment.studentId,value:hasScore&&!missing?Math.max(0,definition[3]-(studentNo%5)):null}));});
      });
    });
  });
  var currentGroups=data.teachingGroups.slice();var previousGroups=[];
  currentGroups.forEach(function(current,index){var previous=baseRecord_('group-2568-'+current.roomId,{termId:previousTerm.id,gradeLevelId:current.gradeLevelId,roomId:current.roomId,subjectId:current.subjectId,name:current.name});previousGroups.push(previous);data.teachingGroups.push(previous);var currentSlot=data.scheduleSlots.filter(function(item){return item.teachingGroupId===current.id;})[0];data.scheduleSlots.push(baseRecord_('schedule-'+previous.id,{teachingGroupId:previous.id,weekday:currentSlot.weekday,period:currentSlot.period,startTime:currentSlot.startTime,endTime:currentSlot.endTime}));var currentRoster=data.enrollments.filter(function(item){return item.teachingGroupId===current.id;});currentRoster.forEach(function(item){data.enrollments.push(baseRecord_('enrollment-'+previous.id+'-'+item.studentId,{teachingGroupId:previous.id,studentId:item.studentId}));});for(var historyNo=0;historyNo<5;historyNo++){var historyDate='2025-08-'+String(4+historyNo*6).padStart(2,'0');var historySession=baseRecord_('session-'+previous.id+'-history-'+historyNo,{teachingGroupId:previous.id,date:historyDate,period:currentSlot.period});data.attendanceSessions.push(historySession);currentRoster.forEach(function(item,studentNo){data.attendanceRecords.push(baseRecord_(historySession.id+':'+item.studentId,{sessionId:historySession.id,studentId:item.studentId,status:studentNo===0&&historyNo%2===0?'ABSENT':'PRESENT'}));});}});
  data.assessmentCategories.push(baseRecord_('category-2568-work',{termId:previousTerm.id,name:'งานและการบ้าน',weight:40}),baseRecord_('category-2568-exam',{termId:previousTerm.id,name:'แบบทดสอบและสอบ',weight:60}));
  [4,5,6].forEach(function(level){var assessmentId='assessment-2568-M'+level;data.assessments.push(baseRecord_(assessmentId,{termId:previousTerm.id,gradeLevelId:'grade-'+level,subjectId:'subject-math',categoryId:'category-2568-exam',title:'สอบปลายภาค 2568',type:'FINAL',status:'REVIEWED',assignedAt:'2025-09-15',dueAt:'2025-09-30',maxScore:40}));previousGroups.filter(function(item){return item.gradeLevelId==='grade-'+level;}).forEach(function(group){data.assessmentTargets.push(baseRecord_('target-'+assessmentId+'-'+group.id,{assessmentId:assessmentId,teachingGroupId:group.id}));data.enrollments.filter(function(item){return item.teachingGroupId===group.id;}).forEach(function(item,index){data.submissions.push(baseRecord_(assessmentId+':'+item.studentId,{assessmentId:assessmentId,studentId:item.studentId,status:'SUBMITTED',submittedAt:'2025-09-30'}));data.scores.push(baseRecord_(assessmentId+':'+item.studentId,{assessmentId:assessmentId,studentId:item.studentId,value:Math.max(18,38-index)}));});});});
  [['4',80],['3.5',75],['3',70],['2.5',65],['2',60],['1.5',55],['1',50],['0',0]].forEach(function(item,index){data.gradeThresholds.push(baseRecord_('threshold-'+item[0],{termId:term.id,grade:item[0],minScore:item[1],order:index+1}));data.gradeThresholds.push(baseRecord_('threshold-2568-'+item[0],{termId:previousTerm.id,grade:item[0],minScore:item[1],order:index+1}));});
  [[-11,'ครูสมหญิง แสงดี','089-111-2233','ลาป่วย','มอบหมายแบบฝึกหัดทบทวน'],[3,'ครูสมชาย ใจดี','081-234-5678','ลากิจส่วนตัว','ฝากใบงานไว้ที่ห้องพักครู'],[18,'ครูกมลชนก ตั้งใจ','086-555-0188','อบรมพัฒนาวิชาชีพ','สอนตามแผนการสอนบทที่ 4']].forEach(function(item){var leaveDate=new Date();leaveDate.setDate(leaveDate.getDate()+item[0]);var dateText=Utilities.formatDate(leaveDate,'Asia/Bangkok','yyyy-MM-dd');data.teacherLeaves.push(baseRecord_('leave-'+dateText,{date:dateText,substituteName:item[1],substitutePhone:item[2],reason:item[3],note:item[4]}));});
  data.teacherLeaves.push(baseRecord_('leave-2025-08-18',{date:'2025-08-18',substituteName:'ครูสมหญิง แสงดี',substitutePhone:'089-111-2233',reason:'ลาป่วย',note:'ข้อมูลตัวอย่างปี 2568'}));
  data.teachingGroups.forEach(function(group,index){var roster=data.enrollments.filter(function(item){return item.teachingGroupId===group.id;});data.behaviorLogs.push(baseRecord_('behavior-'+index+'-positive',{studentId:roster[1].studentId,teachingGroupId:group.id,occurredAt:new Date().toISOString(),sentiment:'POSITIVE',category:'HELPING',note:'ช่วยอธิบายวิธีทำและแบ่งหน้าที่ในกลุ่มได้ดี'}));data.behaviorLogs.push(baseRecord_('behavior-'+index+'-follow',{studentId:roster[4].studentId,teachingGroupId:group.id,occurredAt:new Date().toISOString(),sentiment:'FOLLOW_UP',category:'RESPONSIBILITY',note:'ควรติดตามงานที่ยังส่งไม่ครบและการเตรียมอุปกรณ์'}));});
  var lockedGroup=data.teachingGroups[0];data.enrollments.filter(function(item){return item.teachingGroupId===lockedGroup.id;}).forEach(function(enrollment,index){var total=Math.max(45,92-index*3);var grade=total>=80?'4':total>=75?'3.5':total>=70?'3':total>=65?'2.5':total>=60?'2':total>=55?'1.5':total>=50?'1':'0';data.finalGrades.push(baseRecord_('final-'+lockedGroup.id+'-'+enrollment.studentId,{teachingGroupId:lockedGroup.id,studentId:enrollment.studentId,total:total,grade:grade,lockedAt:new Date().toISOString()}));});
  data.exportRequests.push(baseRecord_('export-sample-1',{format:'PDF',status:'SUCCEEDED',scope:'ROOM',teachingGroupIds:[lockedGroup.id],includeBehavior:false,fileName:'KruNote-ตัวอย่าง-ม4-1.pdf'}));
  Object.keys(data).forEach(function(collection){seedRows_(collection,data[collection]);}); SpreadsheetApp.flush();
}
