var ACTION_COLLECTION = { 'attendance.update':'attendanceRecords', 'submission.update':'submissions', 'score.update':'scores', 'behavior.create':'behaviorLogs', 'teacherLeave.create':'teacherLeaves', 'teacherLeave.update':'teacherLeaves' };
function syncPush_(mutations) {
  if (!Array.isArray(mutations) || mutations.length>50) throw apiError_('BAD_REQUEST','ส่งการเปลี่ยนแปลงได้ครั้งละไม่เกิน 50 รายการ'); var lock=LockService.getScriptLock(); lock.waitLock(30000); var confirmed=[],conflicts=[],failed=[];
  try { mutations.forEach(function(mutation){ try { if (findMutation_(mutation.id)) { confirmed.push(mutation.id); return; } applyMutation_(mutation); logMutation_(mutation); confirmed.push(mutation.id); } catch(error) { if (error.code==='VERSION_CONFLICT') conflicts.push({id:mutation.id,current:error.details.current}); else failed.push({id:mutation.id,code:error.code||'MUTATION_FAILED',message:error.message}); } }); SpreadsheetApp.flush(); } finally { lock.releaseLock(); }
  return { confirmed:confirmed, conflicts:conflicts, failed:failed };
}
function applyMutation_(mutation) {
  var collection=ACTION_COLLECTION[mutation.action]; var payload=mutation.payload;
  if (collection) { validateMutation_(mutation.action,payload); upsertRecord_(collection,payload,mutation.baseVersion); return; }
  if (mutation.action==='attendance.session.upsert') { if (!payload.session || !payload.session.id || !Array.isArray(payload.records)) throw apiError_('INVALID_RECORD','ข้อมูลคาบเช็กชื่อไม่ครบ'); upsertRecord_('attendanceSessions',payload.session,mutation.baseVersion); payload.records.forEach(function(record){validateMutation_('attendance.update',record);upsertRecord_('attendanceRecords',record);}); return; }
  if (mutation.action==='assessment.create' || mutation.action==='assessment.update') { var assessment=payload.assessment||payload; upsertRecord_('assessments',assessment,mutation.baseVersion); (payload.targets||[]).forEach(function(target){upsertRecord_('assessmentTargets',target);}); return; }
  if (mutation.action==='assessmentCategories.replace') { var records=payload.records||[]; var deletedIds=payload.deletedIds||[]; var total=records.reduce(function(sum,item){return sum+Number(item.weight||0);},0); var assessmentsForCategoryValidation=readAll_('assessments'); var currentCategories=readAll_('assessmentCategories'); if (!records.length || Math.abs(total-100)>0.001) throw apiError_('INVALID_CATEGORY_WEIGHT','เปอร์เซ็นต์หมวดคะแนนต้องรวม 100%'); records.forEach(function(record){if(!record.id||!String(record.name||'').trim()||Number(record.weight)<=0||Number(record.weight)>100)throw apiError_('INVALID_CATEGORY','ข้อมูลหมวดคะแนนไม่ถูกต้อง');var current=currentCategories.filter(function(item){return item.id===record.id;})[0];if(current&&Number(current.version)!==Number(record.version))throw apiError_('VERSION_CONFLICT','ข้อมูลถูกแก้จากอุปกรณ์อื่น',{current:current});}); deletedIds.forEach(function(id){if(assessmentsForCategoryValidation.some(function(item){return item.categoryId===id;}))throw apiError_('CATEGORY_IN_USE','ลบหมวดที่มีงานใช้งานอยู่ไม่ได้');}); records.forEach(function(record){upsertRecord_('assessmentCategories',record,Number(record.version||0));}); deletedIds.forEach(function(id){deleteRecord_('assessmentCategories',id);}); return; }
  if (mutation.action==='room.create') { var room=payload.room; var group=payload.group; var slot=payload.scheduleSlot; if(!room||!group||!room.id||!group.id||!String(room.code||'').trim()||!String(room.name||'').trim())throw apiError_('INVALID_ROOM','ข้อมูลห้องเรียนไม่ครบ'); if(!findRecord_('gradeLevels',room.gradeLevelId)||!findRecord_('terms',group.termId)||!findRecord_('subjects',group.subjectId))throw apiError_('INVALID_ROOM_REFERENCE','ไม่พบระดับชั้น ภาคเรียน หรือวิชา'); if(group.roomId!==room.id||group.gradeLevelId!==room.gradeLevelId)throw apiError_('INVALID_ROOM_GROUP','ข้อมูลกลุ่มเรียนไม่ตรงกับห้อง'); if(readAll_('rooms').some(function(item){return item.gradeLevelId===room.gradeLevelId&&String(item.code).toLowerCase()===String(room.code).toLowerCase()&&item.id!==room.id;}))throw apiError_('DUPLICATE_ROOM','มีรหัสห้องนี้ในระดับชั้นแล้ว'); if(slot&&(!slot.id||slot.teachingGroupId!==group.id||Number(slot.weekday)<1||Number(slot.weekday)>5||Number(slot.period)<1||!/^\d{2}:\d{2}$/.test(slot.startTime)||!/^\d{2}:\d{2}$/.test(slot.endTime)||slot.startTime>=slot.endTime))throw apiError_('INVALID_SCHEDULE','ข้อมูลคาบสอนไม่ถูกต้อง'); upsertRecord_('rooms',room,Number(room.version||0)); upsertRecord_('teachingGroups',group,Number(group.version||0)); if(slot)upsertRecord_('scheduleSlots',slot,Number(slot.version||0)); return; }
  if (mutation.action==='students.import') { var students=payload.students||[]; var enrollments=payload.enrollments||[]; if(!students.length||students.length>500)throw apiError_('INVALID_IMPORT','นำเข้าได้ครั้งละ 1–500 คน'); var codes={}; var currentStudents=readAll_('students'); var currentEnrollments=readAll_('enrollments'); students.forEach(function(student){var code=String(student.studentCode||'').trim();if(!student.id||!code||Number(student.number)<1||!String(student.firstName||'').trim()||!String(student.lastName||'').trim())throw apiError_('INVALID_STUDENT','ข้อมูลนักเรียนไม่ครบ');if(codes[code])throw apiError_('DUPLICATE_STUDENT_CODE','รหัสนักเรียนซ้ำในไฟล์: '+code);codes[code]=student.id;var current=currentStudents.filter(function(item){return item.id===student.id;})[0];if(current&&Number(current.version)!==Number(student.version))throw apiError_('VERSION_CONFLICT','ข้อมูลนักเรียนถูกแก้จากอุปกรณ์อื่น',{current:current});}); enrollments.forEach(function(enrollment){if(!enrollment.id||!codes[String(students.filter(function(item){return item.id===enrollment.studentId;})[0]&&students.filter(function(item){return item.id===enrollment.studentId;})[0].studentCode||'')]||!findRecord_('teachingGroups',enrollment.teachingGroupId))throw apiError_('INVALID_ENROLLMENT','ข้อมูลการเข้าห้องไม่ถูกต้อง');var current=currentEnrollments.filter(function(item){return item.id===enrollment.id;})[0];if(current&&Number(current.version)!==Number(enrollment.version))throw apiError_('VERSION_CONFLICT','ข้อมูลรายชื่อถูกแก้จากอุปกรณ์อื่น',{current:current});}); students.forEach(function(student){upsertRecord_('students',student,Number(student.version||0));}); enrollments.forEach(function(enrollment){upsertRecord_('enrollments',enrollment,Number(enrollment.version||0));}); return; }
  if (mutation.action==='grades.lock') { (payload.records||[]).forEach(function(record){upsertRecord_('finalGrades',record);}); return; }
  throw apiError_('UNKNOWN_MUTATION','ไม่รองรับ '+mutation.action);
}
function validateMutation_(action,payload) { if (!payload || !payload.id) throw apiError_('INVALID_RECORD','ข้อมูลไม่มี id'); if (action==='attendance.update' && ['PRESENT','LATE','ABSENT','LEAVE'].indexOf(payload.status)<0) throw apiError_('INVALID_STATUS','สถานะเข้าเรียนไม่ถูกต้อง'); if (action==='submission.update' && ['SUBMITTED','LATE','MISSING','EXEMPT'].indexOf(payload.status)<0) throw apiError_('INVALID_STATUS','สถานะส่งงานไม่ถูกต้อง'); if (action==='score.update') { var assessment=findRecord_('assessments',payload.assessmentId); if (!assessment || payload.value!==null && (Number(payload.value)<0 || Number(payload.value)>Number(assessment.maxScore))) throw apiError_('INVALID_SCORE','คะแนนเกินช่วงที่กำหนด'); } }
function findMutation_(id) { var sheet=sheetFor_('MutationLog'); if (sheet.getLastRow()<2) return false; return sheet.getRange(2,1,sheet.getLastRow()-1,1).createTextFinder(id).matchEntireCell(true).findNext()!==null; }
function logMutation_(mutation) { var now=new Date().toISOString(); sheetFor_('MutationLog').appendRow([mutation.id,JSON.stringify({id:mutation.id}),1,now]); }
